#!/bin/bash
# ==============================================================
# cap_cmomf LVS checks.
#
# The sibling of cap_cmomi_checks/run_lvs.sh and deliberately its mirror image,
# same structure and same verdict vocabulary. The unit regression can only hold
# cases that pass, so everything that has to fail, and everything that documents
# a limitation, lives here. Each case declares the verdict it expects and the
# script fails if a case stops behaving the way it is recorded to behave.
#
# Three verdicts are possible. PASS and FAIL are the two comparison outcomes.
# ERROR means the extractor rejected the layout: the run aborts before the
# comparison, so there is no verdict. A partial extracted netlist is still
# written, holding whatever devices the extractor did make sense of.
#
# The cases marked PASS are not filler. Several of them pass only because the
# deck matches cap_cmomf topologically and ignores its parameters; recording
# them means that if someone tightens the comparison, the change surfaces here
# instead of silently altering what LVS accepts.
#
# Cases run in flat mode unless a sixth argument says otherwise.
#
# Layouts are generated by testing/create_cap_cmomf_testcases.py.
# ==============================================================

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
RUN_LVS="${SCRIPT_DIR}/../../../../run_lvs.py"
RUN_ROOT="${TMPDIR:-/tmp}/sg13g2_cap_cmomf_checks_$(date +%Y_%m_%d_%H_%M_%S)"

FAILED=0

run_case() {
  local case_name="$1"
  local layout="$2"
  local topcell="$3"
  local netlist="$4"
  local expected="$5"
  local run_mode="${6:-flat}"
  local case_dir="${RUN_ROOT}/${case_name}"
  local case_log="${case_dir}/${case_name}.log"

  mkdir -p "${case_dir}"

  echo "Running ${case_name} (expected: ${expected}, mode: ${run_mode})"
  python3 "${RUN_LVS}" \
    --layout="${SCRIPT_DIR}/${layout}" \
    --topcell="${topcell}" \
    --netlist="${SCRIPT_DIR}/${netlist}" \
    --run_mode="${run_mode}" \
    --run_dir="${case_dir}" \
    --ignore_top_ports_mismatch > "${case_log}" 2>&1 || true

  local actual="UNKNOWN"
  if grep -q "Congratulations! Netlists match" "${case_log}"; then
    actual="PASS"
  elif grep -q "ERROR : Netlists don't match" "${case_log}"; then
    actual="FAIL"
  elif grep -q "Errors encountered during netlist extraction" "${case_log}"; then
    # The extractor reported an error(), so KLayout raises instead of handing
    # the netlist to the comparison. No verdict is produced, which is the
    # intended outcome for a layout the extractor cannot make sense of.
    actual="ERROR"
  fi

  if [[ "${actual}" == "${expected}" ]]; then
    echo "  -> ${case_name}: OK (actual=${actual})"
  else
    echo "  -> ${case_name}: UNEXPECTED (actual=${actual}, expected=${expected})"
    FAILED=$((FAILED + 1))
  fi
}

# --- the deck detects what it should ----------------------------------------

# Golden: three caps in series, A-N1-N2-B.
run_case "1_chain_match" \
  "cmomf_chain.gds" "cmomf_chain" "chain_match.cdl" "PASS"

# A device present in the layout and absent from the schematic.
run_case "2_chain_missing_device" \
  "cmomf_chain.gds" "cmomf_chain" "chain_missing.cdl" "FAIL"

# The two plates of one cap tied together by a Metal5 wire. Reported as a
# missing device rather than as a short: KLayout drops a device whose terminals
# all land on the same net, so the shorted cap never reaches the comparison.
run_case "3_shorted_plates" \
  "cmomf_shorted.gds" "cmomf_shorted" "shorted.cdl" "FAIL"

# Two caps under one merged Recog.momf marker. Four ports in one cluster, so
# CapMomExtractor cannot tell which pins belong to which device and reports an
# extraction error naming the device it was extracting.
run_case "4_merged_markers" \
  "cmomf_merged.gds" "cmomf_merged" "merged.cdl" "ERROR"

# --- terminal symmetry ------------------------------------------------------

# The middle cap's terminals exchanged in the netlist, and nothing else: the
# connectivity graph is identical. The extractor picks the two ports by geometry
# and never reads their pin names, so the order it produces is arbitrary and
# DeviceCustomMIM declares the cap_cmomf terminals equivalent.
run_case "5_terminals_swapped" \
  "cmomf_chain.gds" "cmomf_chain" "chain_swapped.cdl" "PASS"

# The same statement made in layout: the golden netlist against a chain whose
# last cap is mirrored about the y axis. Mirroring moves PLUS from the left edge
# to the right one, and the extractor sorts its two ports by x, so the terminals
# come out exchanged for a circuit that did not change. This is the case that
# bites in practice, and it only passes because DeviceCustomMIM declares the two
# terminals equivalent for any device whose name contains 'cmom'. That gate used
# to read 'cmomi' and covered cap_cmomi alone.
run_case "6_mirrored_placement" \
  "cmomf_mirrored.gds" "cmomf_mirrored" "mirrored.cdl" "PASS"

# --- recorded limitations: these pass, and that is the finding ---------------

# w/l declared as 99u x 1u against a 5x5 layout. Both are is_primary=false.
run_case "7_wrong_wl_accepted" \
  "cmomf_chain.gds" "cmomf_chain" "chain_wrong_wl.cdl" "PASS"

# mmin/mmax declared as 4..5 against a 1..5 layout. Same footprint, same marker
# bbox, pins on the same metal, so the extractor cannot tell them apart. Two
# coupled metals instead of five, so the capacitance differs by two and a half.
run_case "8_wrong_metal_band_accepted" \
  "cmomf_chain.gds" "cmomf_chain" "chain_wrong_band.cdl" "PASS"

# A multiplier the layout does not have. m is declared is_primary=true on
# DeviceCustomMIM, so it looks compared, but map_capacitor_params only sets it
# when the model name contains 'mim', and cap_cmomf does not, so the value is
# read off the card and dropped and both sides keep the default of 1. m is also
# the only token beyond w/l that the xschem symbol's lvs_format emits.
run_case "9_wrong_multiplier_accepted" \
  "cmomf_chain.gds" "cmomf_chain" "chain_wrong_m.cdl" "PASS"

# --- markers, hierarchy -----------------------------------------------------

# The merged-marker construction with nothing else in the cell. Without the
# extraction error in custom_mom_extractor.lvs the circuit would be left empty,
# drop out of the layout netlist, and the comparison would match any schematic
# at all. Nothing else in this PDK's flow would catch that.
run_case "10_all_devices_dropped" \
  "cmomf_all_dropped.gds" "cmomf_all_dropped" "all_dropped.cdl" "ERROR"

# One cap_cmomf beside one cap_cmomi. The two are told apart by their marker
# alone, 99/40 against 99/39, and sharing one would make a single geometry
# extract as both devices. No counterpart on the cap_cmomi side.
run_case "11_coexists_with_cap_cmomi" \
  "cmomf_coexist.gds" "cmomf_coexist" "coexist.cdl" "PASS"

# The same missing-device perturbation as case 2, on the hierarchical unit
# layout, in deep mode. Case 2 catches it. This one does NOT, and the PASS is
# the finding rather than the behaviour anyone wants: every cap here sits in a
# sub-cell with no net crossing its boundary, the layout netlist comes out
# empty, and compare then has no pair left to compare and returns true. The
# .lvsdb still carries the device abstract, so extraction is not what fails.
#
# cap_cmomi empties the same way on the same construction, so the hole belongs
# to neither device. That was observed on the ihp-sg13cmos5l side, where both
# devices have a deep case; nothing in this tree demonstrates it for cap_cmomi.
# It is tracked as ihp-sg13cmos5l#91, and that
# PDK refuses the vacuous half of it in its own sg13cmos5l.lvs by counting the
# devices on both sides; this one has no such guard. Read this case together
# with case 13, the same hierarchy wired to the top, which compares for real.
#
# The layout is referenced across from the unit testcase rather than copied, so
# the flat and deep runs cannot drift apart.
run_case "12_deep_empty_extraction_unreported" \
  "../../unit/cap_devices/layout/cap_cmomf_hier.gds" "cap_cmomf_hier" \
  "hier_deep_missing.cdl" "PASS" "deep"

# The same hierarchy as case 12, with one Metal5 route in the top cell joining
# the two sub-cells, so a net crosses a cell boundary and the sub-circuits keep
# a pin. Deep extracts both caps and the comparison is real. This case is what
# makes case 12 mean anything: on its own, case 12 would keep reporting a match
# even if deep extraction broke outright, and the suite would stay green.
run_case "13_deep_wired_hierarchy" \
  "cmomf_hier_wired.gds" "cmomf_hier_wired" "hier_wired.cdl" "PASS" "deep"

if [[ "${FAILED}" -ne 0 ]]; then
  echo "cap_cmomf checks FAILED (${FAILED} case(s) did not behave as recorded)."
  echo "Logs: ${RUN_ROOT}"
  exit 1
fi

echo "cap_cmomf checks PASSED (13 cases behaved as recorded)."
echo "Logs: ${RUN_ROOT}"
