#!/bin/bash
# ==============================================================
# cap_cmomi LVS checks.
#
# The unit regression can only hold cases that pass, so everything that has to
# fail, and everything that documents a limitation, lives here. Each case
# declares the verdict it expects and the script fails if a case stops
# behaving the way it is recorded to behave.
#
# Three verdicts are possible. PASS and FAIL are the two comparison outcomes.
# ERROR means the extractor rejected the layout: the run aborts before the
# comparison, so there is no verdict. A partial extracted netlist is still
# written, holding whatever devices the extractor did make sense of.
#
# The cases marked PASS are not filler. Several of them pass only because the
# deck matches cap_cmomi topologically and ignores its parameters; recording
# them means that if someone tightens the comparison, the change surfaces here
# instead of silently altering what LVS accepts.
#
# Cases run in flat mode unless a sixth argument says otherwise.
#
# Layouts are generated by testing/create_cap_cmomi_testcases.py.
# ==============================================================

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
RUN_LVS="${SCRIPT_DIR}/../../../../run_lvs.py"
RUN_ROOT="${TMPDIR:-/tmp}/sg13cmos5l_cap_cmomi_checks_$(date +%Y_%m_%d_%H_%M_%S)"

FAILED=0

run_case() {
  local case_name="$1"
  local layout="$2"
  local topcell="$3"
  local netlist="$4"
  local expected="$5"
  local run_mode="${6:-flat}"
  local case_dir="${RUN_ROOT}/${case_name}"
  local case_log="${case_dir}/${case_name}.log"

  mkdir -p "${case_dir}"

  echo "Running ${case_name} (expected: ${expected}, mode: ${run_mode})"
  python3 "${RUN_LVS}" \
    --layout="${SCRIPT_DIR}/${layout}" \
    --topcell="${topcell}" \
    --netlist="${SCRIPT_DIR}/${netlist}" \
    --run_mode="${run_mode}" \
    --run_dir="${case_dir}" \
    --ignore_top_ports_mismatch > "${case_log}" 2>&1 || true

  local actual="UNKNOWN"
  if grep -q "Congratulations! Netlists match" "${case_log}"; then
    actual="PASS"
  elif grep -q "ERROR : Netlists don't match" "${case_log}"; then
    actual="FAIL"
  elif grep -q "Errors encountered during netlist extraction" "${case_log}"; then
    # The extractor reported an error(), so KLayout raises instead of handing
    # the netlist to the comparison. No verdict is produced, which is the
    # intended outcome for a layout the extractor cannot make sense of.
    actual="ERROR"
  fi

  if [[ "${actual}" == "${expected}" ]]; then
    echo "  -> ${case_name}: OK (actual=${actual})"
  else
    echo "  -> ${case_name}: UNEXPECTED (actual=${actual}, expected=${expected})"
    FAILED=$((FAILED + 1))
  fi
}

# --- the deck detects what it should ----------------------------------------

# Golden: three caps in series, A-N1-N2-B.
run_case "1_chain_match" \
  "cmomi_chain.gds" "cmomi_chain" "chain_match.cdl" "PASS"

# A device present in the layout and absent from the schematic.
run_case "2_chain_missing_device" \
  "cmomi_chain.gds" "cmomi_chain" "chain_missing.cdl" "FAIL"

# The two stacked plates of a 'same' feed cap shorted by a Via3: proves the
# per-metal pin connect is what keeps them on separate nets.
run_case "3_same_feed_shorted" \
  "cmomi_short_same.gds" "cmomi_short_same" "short_same.cdl" "FAIL"

# Two caps under one merged Recog.mom marker. Four ports in one cluster, so
# CapMomExtractor cannot tell which pins belong to which device and reports an
# extraction error naming the marker.
run_case "4_merged_markers" \
  "cmomi_merged.gds" "cmomi_merged" "merged.cdl" "ERROR"

# --- terminal symmetry ------------------------------------------------------

# The middle cap's terminals exchanged, and nothing else: the connectivity graph
# is identical. The extractor picks the two ports by geometry and never reads
# their pin names, so the order it produces is arbitrary and DeviceCustomMIM
# declares the cap_cmomi terminals equivalent. Expected to PASS; before that
# equivalence this failed, which meant a mirrored placement of a symmetric
# device was reported as a mismatch.
run_case "5_terminals_swapped" \
  "cmomi_chain.gds" "cmomi_chain" "chain_swapped.cdl" "PASS"

# --- recorded limitations: these pass, and that is the finding ---------------

# w/l declared as 99u x 1u against a 5x5 layout. Both are is_primary=false.
run_case "6_wrong_wl_accepted" \
  "cmomi_chain.gds" "cmomi_chain" "chain_wrong_wl.cdl" "PASS"

# mmin/mmax declared as 3..4 against a 1..4 layout. Same footprint, same marker
# bbox, pins on the same metal, so the extractor cannot tell them apart. Two
# coupled metals instead of four, so the capacitance differs by roughly 2x.
run_case "7_wrong_metal_band_accepted" \
  "cmomi_chain.gds" "cmomi_chain" "chain_wrong_band.cdl" "PASS"

# feed declared as 'same' against a 'double' layout.
run_case "8_wrong_feed_accepted" \
  "cmomi_chain.gds" "cmomi_chain" "chain_wrong_feed.cdl" "PASS"

# feed='none' is an array with no feed structure, so its rows are never tied
# into two plates. It still carries two MkPins, so it extracts as an ordinary
# cap_cmomi between whatever two bars the pins land on.
run_case "9_feed_none_accepted" \
  "cmomi_feed_none.gds" "cmomi_feed_none" "feed_none.cdl" "PASS"

# The same merged-marker construction with nothing else in the cell. Before the
# extractor reported this through error(), the circuit was left empty, dropped
# out of the layout netlist, and the comparison matched any schematic at all: a
# netlist of twelve caps passed against a layout that extracted none. The
# extraction error is what closes that.
run_case "10_all_devices_dropped" \
  "cmomi_all_dropped.gds" "cmomi_all_dropped" "all_dropped.cdl" "ERROR"

# A multiplier the layout does not have. m is declared is_primary=true on
# DeviceCustomMIM, so it looks compared, but map_capacitor_params only sets it
# when the model name contains 'mim', and cap_cmomi does not, so the value is
# read off the card and dropped and both sides keep the default of 1. m is also
# the only token beyond w/l that the xschem symbol's lvs_format emits.
run_case "11_wrong_multiplier_accepted" \
  "cmomi_chain.gds" "cmomi_chain" "chain_wrong_m.cdl" "PASS"

# The same missing-device perturbation as case 2, on the hierarchical unit
# layout, in deep mode. Case 2 fails on the comparison; this one fails on the
# empty-extraction guard, which runs after a comparison that had nothing left to
# compare and returned true, because every cap here sits in a sub-cell with
# no net crossing its boundary and the layout netlist comes out empty. The
# extraction hole is still open: what the deck no longer does is call an empty
# netlist a match, which is how this case passed before the guard. Read it
# together with case 13, which is the same hierarchy wired to the top and must
# pass; the cause itself is not diagnosed. The layout is referenced across from
# the unit testcase rather than copied, so the flat and deep runs cannot drift
# apart.
run_case "12_deep_empty_extraction_reported" \
  "../../unit/cap_devices/layout/cap_cmomi_hier.gds" "cap_cmomi_hier" \
  "hier_deep_missing.cdl" "FAIL" "deep"

# The same hierarchy as case 12, with one Metal4 strap in the top cell joining
# the two sub-cells, so a net crosses a cell boundary and the sub-circuits keep
# a pin. Deep extracts both caps and the comparison is real. This case is what
# makes case 12's failure mean something: on its own, case 12 would keep failing
# even if deep extraction broke outright, and the suite would stay green.
run_case "13_deep_wired_hierarchy" \
  "cmomi_hier_wired.gds" "cmomi_hier_wired" "hier_wired.cdl" "PASS" "deep"

if [[ "${FAILED}" -ne 0 ]]; then
  echo "cap_cmomi checks FAILED (${FAILED} case(s) did not behave as recorded)."
  echo "Logs: ${RUN_ROOT}"
  exit 1
fi

echo "cap_cmomi checks PASSED (13 cases behaved as recorded)."
echo "Logs: ${RUN_ROOT}"
