//******************************************************************************
//
// Copyright 2026 IHP PDK Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//******************************************************************************

//******************************************************************************
// SG13G2 MOSLV RF (NQS) paramsets
//
// Aggregate source for building low-voltage MOS RF device plugins. It
// includes the PSPNQS103VA compact model and the paramsets for different
// low-voltage MOS RF device variants.
//******************************************************************************

`pragma modelgen nogen-module
`include "psp103_nqs.va"

`include "paramsets/sg13g2_moslv_rf_nmos.va"
`include "paramsets/sg13g2_moslv_rf_pmos.va"
